ServerRoot "/usr/local/apache2"
Listen 8080
ServerName localhost
PidFile /tmp/httpd.pid
DefaultRuntimeDir /tmp
LoadModule mpm_event_module modules/mod_mpm_event.so
LoadModule unixd_module modules/mod_unixd.so
LoadModule authz_core_module modules/mod_authz_core.so
LoadModule dir_module modules/mod_dir.so
LoadModule mime_module modules/mod_mime.so
LoadModule log_config_module modules/mod_log_config.so
LoadModule headers_module modules/mod_headers.so
LoadModule rewrite_module modules/mod_rewrite.so
LoadModule filter_module modules/mod_filter.so
LoadModule deflate_module modules/mod_deflate.so
LoadModule negotiation_module modules/mod_negotiation.so
User nobody
Group nogroup
ServerTokens Prod
ServerSignature Off
TraceEnable Off
ErrorLog /proc/self/fd/2
LogLevel warn
LogFormat "%h %t \"%r\" %>s %b" common
CustomLog /proc/self/fd/1 common
TypesConfig conf/mime.types
DocumentRoot "/usr/local/apache2/htdocs"
<Directory "/">
    AllowOverride None
    Require all denied
</Directory>
<Directory "/usr/local/apache2/htdocs">
    Options FollowSymLinks
    AllowOverride All
    Require all granted
</Directory>
