name: Check and build website

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  website:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          persist-credentials: false
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: '22'
          cache: npm
      - run: npm ci --ignore-scripts
      - run: npm run check
      - run: npm run check:apache
      - name: Upload website files (also suitable for normal hosting)
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: sith-assembly-webhosting
          path: dist/
          include-hidden-files: true
          if-no-files-found: error
          retention-days: 14
