# To better understand this file read this:
# https://docs.ionos.space/docs/github-actions-customization/

name: "Deploy Now: Execute Build"

on:
  workflow_call:
    inputs:
      site-url:
        required: true
        type: string
      branch-id:
        required: true
        type: string
    secrets:
      IONOS_API_KEY:
        required: true

permissions:
  contents: read

env:
  DEPLOYMENT_FOLDER: dist

jobs:
# Please do not rename this job
  build-project:
    name: build SithAssemblyUI
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: v22.x

      - name: Build Node assets
        env:
          CI: true
          SITE_URL: ${{ inputs.site-url }}
        run: |
          npm ci --ignore-scripts
          npm run check
          npm run check:apache

# Please do not touch the following action
      - name: Store deployment content
        uses: ionos-deploy-now/artifact-action@184a369b679287c06ff3d4392cf57bf0fd32656e # v1
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          service-host: api-eu.ionos.space
          project-id: f06760fe-4f7e-4ffc-81b7-ba7fdc5cc324
          branch-id: ${{ inputs.branch-id }}
          version: ${{ github.sha }}
          folder: ${{ env.DEPLOYMENT_FOLDER }}
          config-file: .deploy-now/SithAssemblyUI/config.yaml
          action: upload
