# IONOS orchestration restricted to the current production branch.
# Build steps can be customized in the SithAssemblyUI-build.yaml.
# More information under https://docs.ionos.space/docs/github-actions-customization/
# version: 2022-07-21

name: "Deploy Now: Orchestration"
run-name: "Deploy Now: Build SithAssemblyUI · ${{ github.event.head_commit.message || format('Triggered by {0}', github.triggering_actor) }}"

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ionos-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  retrieve-project:
    if: ${{ github.ref == 'refs/heads/main' }}
    name: check readiness
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      deployment-enabled: ${{ fromJson(steps.project.outputs.info).deployment-enabled }}
      branch-id: ${{ fromJson(steps.project.outputs.info).branch-id }}
    steps:
      - name: Fetch project data
        uses: ionos-deploy-now/project-action@95e8bc58cdc22a86df7709493de6054179881470 # v1
        id: project
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          service-host: api-eu.ionos.space
          project-id: f06760fe-4f7e-4ffc-81b7-ba7fdc5cc324
          action: retrieve-info


  build:
    name: build
    needs: retrieve-project
    if: ${{ needs.retrieve-project.outputs.deployment-enabled == 'true' }}
    uses: ./.github/workflows/SithAssemblyUI-build.yaml
    with:
      site-url: https://IONOS_DEPLOY_NOW_SITE_URL
      branch-id: ${{ needs.retrieve-project.outputs.branch-id }}
    secrets:
      IONOS_API_KEY: ${{ secrets.IONOS_API_KEY }}

  deploy:
    name: trigger deployment
    needs:
      - retrieve-project
      - build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Dispatch deployment(s)
        uses: ionos-deploy-now/project-action@95e8bc58cdc22a86df7709493de6054179881470 # v1
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          service-host: api-eu.ionos.space
          project-id: f06760fe-4f7e-4ffc-81b7-ba7fdc5cc324
          branch-id: ${{ needs.retrieve-project.outputs.branch-id }}
          action: dispatch-deployments
